---
info:
  component: User MicroService

server:
  port: 0
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

spring:
  datasource:  
    url: jdbc:mariadb://dbinstance:3306/user
    username: root
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver
