---
info:
  component: User MicroService

server:
  port: 0
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/

spring:
  datasource:  
    url: jdbc:mariadb://localhost:3306/user
    username: root
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver
  oauth2:
    resource:
      userInfoUri: https://www.googleapis.com/plus/v1/people/me
      preferTokenInfo: false
   
